In [1]:
import pandas as pd
from os import *
import os
from random import Random
import numpy as np
import json
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel(".\Muestras\FW 01.xlsx")

In [3]:
path = ".\Muestras"
path2 = ".\Muestras\DataSet"
path3 = ".\Muestras\Resultados"

os.makedirs('.\Muestras\Resultados', exist_ok=True)
os.makedirs('.\Muestras\DataSet', exist_ok=True)

In [4]:
Puntos={'Rio_Paraguay':('FW 01.xlsx','FW 02.xlsx','FW 03.xlsx'),
        'Arroyo_negla':('FW 104-ZA.xlsx','FW 201-ST.xlsx','FW 320-ST.xlsx',),
        'Arroyo_Hermosa':('FW 315-HE.xlsx',),
        'Arroyo_Trementina':('FW 304-HE.xlsx','FW 100-GASL.xlsx','FW 200-SLTR.xlsx','FW 208-TR.xlsx','FW 205-TR.xlsx','FW 109-MYRZ.xlsx','FW 317-RZ.xlsx',),
        'Arroyo_Pitanohaga':('FW 210-ZM.xlsx','FW 212-MC.xlsx','FW 318-VS.xlsx','FW 319-SO.xlsx',),
        'Rio_Aquidaban':('FW 110-LB.xlsx','FW 111-LB.xlsx',),
        'Arroyo_Laguna_Penayo':'FW 316-CR.xlsx'}

In [5]:
Puntos.keys()

dict_keys(['Rio_Paraguay', 'Arroyo_negla', 'Arroyo_Hermosa', 'Arroyo_Trementina', 'Arroyo_Pitanohaga', 'Rio_Aquidaban', 'Arroyo_Laguna_Penayo'])

In [202]:
x=listdir(path)

In [6]:
## Genera Diccionarios de los DataFrames
i=0
Todo={}
mapa={}
Rio_Paraguay, Arroyo_negla, Arroyo_Hermosa, Arroyo_Trementina,Arroyo_Pitanohaga, Rio_Aquidaban, Arroyo_Laguna_Penayo={},{},{},{},{},{},{}
for x in listdir(path):
    
#     df=f"df_{i}"
#     Todo[df]=pd.read_excel(f"{path}\{x}")
    
    df=x.replace(".xlsx", "")
    mapa[df]=x
    if x in Puntos['Rio_Paraguay']:
        Rio_Paraguay[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Rio_Paraguay']))
    elif x in Puntos['Arroyo_negla']:
        Arroyo_negla[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Arroyo_negla']))
    elif x in Puntos['Arroyo_Hermosa']:
        Arroyo_Hermosa[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Arroyo_Hermosa']))
    elif x in Puntos['Arroyo_Trementina']:
        Arroyo_Trementina[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Arroyo_Trementina']))
    elif x in Puntos['Arroyo_Pitanohaga']:
        Arroyo_Pitanohaga[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Arroyo_Pitanohaga']))
    elif x in Puntos['Rio_Aquidaban']:
        Rio_Aquidaban[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Rio_Aquidaban']))
    elif x in Puntos['Arroyo_Laguna_Penayo']:
        Arroyo_Laguna_Penayo[df]=pd.read_excel(f"{path}\{x}")
        Todo[df]=pd.read_excel(f"{path}\{x}")
#         print (str(x) +" " +str (x in Puntos['Arroyo_Laguna_Penayo']))
    i+=1

In [7]:
## Elimina las columnas que no se necesitan para el analsis 
for n in Rio_Paraguay:
    Rio_Paraguay[n].dropna(axis='columns',how='all',inplace=True)
    Rio_Paraguay[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02','MAR'],inplace=True)
for n in Arroyo_negla:
    Arroyo_negla[n].dropna(axis='columns',how='all',inplace=True)
    Arroyo_negla[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
for n in Arroyo_Hermosa:
    Arroyo_Hermosa[n].dropna(axis='columns',how='all',inplace=True)
    Arroyo_Hermosa[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
for n in Arroyo_Trementina:
    Arroyo_Trementina[n].dropna(axis='columns',how='all',inplace=True)
    Arroyo_Trementina[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
for n in Arroyo_Pitanohaga:
    Arroyo_Pitanohaga[n].dropna(axis='columns',how='all',inplace=True)
    Arroyo_Pitanohaga[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
for n in Rio_Aquidaban:
    Rio_Aquidaban[n].dropna(axis='columns',how='all',inplace=True)
    Rio_Aquidaban[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
for n in Arroyo_Laguna_Penayo:
    Arroyo_Laguna_Penayo[n].dropna(axis='columns',how='all',inplace=True)
    limites=Arroyo_Laguna_Penayo[n]['LIMITES RESOLUCIÓN 222/02']
    Arroyo_Laguna_Penayo[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)

In [13]:
## Funcion de Formateo de datos 
def formatData(data):
    data=str(data)
#     data=data.replace('< ','0')
#     data=data.replace('> ','0')
#     data=data.replace('<','0')
#     data=data.replace('>','0')
    if '<' in data or '>' in data or 'S' in data or 'E'==data:
        data=np.NaN
        return data
    else:
        data=data.replace(',','.')
        data=data.replace('O ','0.')
        return float(data)

In [8]:
Rio_Paraguay

{'FW 01':         PARÁMETROS FW 01-PY RAINY SEASON 2021 DRY SEASON       FEB
 0      Temperatura del agua                26       19.7      30.9
 1    Potencial de hidrogeno              7.26       6.94       7.1
 2   Conductividad eléctrica             169.3        114      87.3
 3          Oxígeno disuelto              7.03       9.47      6.35
 4                  Turbidez              41.2       14.1      15.2
 ..                      ...               ...        ...       ...
 68             Imidacloprid            < 0,09     < 0,09  < 0,0900
 69            Metilparaoxon              < 25       < 25    < 25,0
 70              Tiametoxam              < 0,6      < 0,6   < 0,600
 71            Sulfluramida              < 0,6      < 0,6   < 0,600
 72                 Fipronil            < 0,01     < 0,01    < 0,01

 [73 rows x 4 columns],
 'FW 02':         PARÁMETROS FW 02-PY RAINY SEASON 2021 DRY SEASON 2022       FEB
 0      Temperatura del agua                25            19.2      30.8
 1    Potencial de hidrogeno              7.29            7.07      7.06
 2   Conductividad eléctrica             171.8             316        92
 3          Oxígeno disuelto              7.26            9.53       6.4
 4                  Turbidez              44.6            15.5      23.4
 ..                      ...               ...             ...       ...
 68             Imidacloprid            < 0,09          < 0,09  < 0,0900
 69            Metilparaoxon              < 25            < 25    < 25,0
 70              Tiametoxam              < 0,6           < 0,6   < 0,600
 71            Sulfluramida              < 0,6           < 0,6   < 0,600
 72                 Fipronil            < 0,01          < 0,01    < 0,01

 [73 rows x 4 columns],
 'FW 03':         PARÁMETROS FW 03-PY RAINY SEASON 2021 DRY SEASON 2021       FEB
 0      Temperatura del agua         S/D - NIT       S/D - NIT      30.7
 1    Potencial de hidrogeno         S/D - NIT       S/D - NIT      7.14
 2   Conductividad eléctrica         S/D - NIT       S/D - NIT      90.2
 3          Oxígeno disuelto         S/D - NIT       S/D - NIT      6.49
 4                  Turbidez         S/D - NIT       S/D - NIT      25.6
 ..                      ...               ...             ...       ...
 68             Imidacloprid         S/D - NIT       S/D - NIT  < 0,0900
 69            Metilparaoxon         S/D - NIT       S/D - NIT    < 25,0
 70              Tiametoxam          S/D - NIT       S/D - NIT   < 0,600
 71            Sulfluramida          S/D - NIT       S/D - NIT   < 0,600
 72                 Fipronil         S/D - NIT       S/D - NIT    < 0,01

 [73 rows x 4 columns]}

In [14]:
### Analisis de Cuenca del Rio Paraguay - Merge de los dataframes ###
df_Rio_Paraguay=Rio_Paraguay['FW 01']
df_Rio_Paraguay=df_Rio_Paraguay.merge(Rio_Paraguay['FW 02'], left_on='PARÁMETROS FW 01-PY', right_on='PARÁMETROS FW 02-PY')
df_Rio_Paraguay=df_Rio_Paraguay.merge(Rio_Paraguay['FW 03'], left_on='PARÁMETROS FW 01-PY', right_on='PARÁMETROS FW 03-PY')
# df_Rio_Paraguay.columns

## Elimnar las columas repetidas por el merge
df_Rio_Paraguay.drop(columns=['PARÁMETROS FW 02-PY','PARÁMETROS FW 03-PY'],inplace=True)

# Generar Archivo Data Set ORIGINAL Cause #1
df_Rio_Paraguay.dropna(axis='columns',how='all').to_excel(f"{path2}\Original_Rio_Paraguay.xlsx")

In [15]:
## Limpieza de Datos - 
for i in df_Rio_Paraguay.columns[1:]:
    df_Rio_Paraguay[i]=df_Rio_Paraguay[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_Rio_Paraguay[i]=df_Rio_Paraguay[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_Rio_Paraguay[i]=df_Rio_Paraguay[i].apply(formatData)
    df_Rio_Paraguay[i] = df_Rio_Paraguay[i].astype(float)

In [16]:
df_Rio_Paraguay

,PARÁMETROS FW 01-PY,RAINY SEASON 2021_x,DRY SEASON,FEB_x,RAINY SEASON 2021_y,DRY SEASON 2022,FEB_y,RAINY SEASON 2021,DRY SEASON 2021,FEB
0,Temperatura del agua,26.00,19.70,30.90,25.00,19.20,30.80,NaN,NaN,30.70
1,Potencial de hidrogeno,7.26,6.94,7.10,7.29,7.07,7.06,NaN,NaN,7.14
2,Conductividad eléctrica,169.30,114.00,87.30,171.80,316.00,92.00,NaN,NaN,90.20
3,Oxígeno disuelto,7.03,9.47,6.35,7.26,9.53,6.40,NaN,NaN,6.49
4,Turbidez,41.20,14.10,15.20,44.60,15.50,23.40,NaN,NaN,25.60
...,...,...,...,...,...,...,...,...,...,...
67,Imidacloprid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Metilparaoxon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Tiametoxam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Sulfluramida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Fipronil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
## Nuevo Data Frame de promedios por campana
df_Rio_Paraguay_Prom=pd.DataFrame()

df_Rio_Paraguay_Prom["PARÁMETROS"]=df_Rio_Paraguay['PARÁMETROS FW 01-PY']
df_Rio_Paraguay_Prom["RAINY SEASON 2021"]=df_Rio_Paraguay[['RAINY SEASON 2021_x','RAINY SEASON 2021_y','RAINY SEASON 2021']].mean(axis=1,numeric_only=True,skipna=True)
df_Rio_Paraguay_Prom["DRY SEASON 2021"]=df_Rio_Paraguay[['DRY SEASON','DRY SEASON 2021','DRY SEASON 2022']].mean(axis=1,numeric_only=True,skipna=True)
df_Rio_Paraguay_Prom["RAINY SEASON 2022"]=df_Rio_Paraguay[['FEB_x','FEB_y','FEB']].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Cause #1
df_Rio_Paraguay_Prom
df_Rio_Paraguay_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_Rio_Paraguay.xlsx")
###########################################################################################################################

In [18]:
### Analisis de Cuenca del Arroyo negla - Merge de los dataframes ###

n=0
dropend=[]
## MERGE
# print(Arroyo_negla.keys())
df_Arroyo_negla=pd.DataFrame()
for i in Arroyo_negla.keys():
    if n==0:
        df_Arroyo_negla=Arroyo_negla[i]
        first=df_Arroyo_negla.columns[0]
    if n>0:
        print(Arroyo_negla[i].columns[0])
        df_Arroyo_negla=df_Arroyo_negla.merge(Arroyo_negla[i], left_on=first, right_on=Arroyo_negla[i].columns[0])
        dropend.append(Arroyo_negla[i].columns[0])
    n+=1
    
## Elimnar las columas repetidas por el merge
df_Arroyo_negla.drop(columns=dropend,inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_Arroyo_negla.dropna(axis='columns',how='all').to_excel(f"{path2}\Original_Arroyo_negla.xlsx")
## Limpieza de Datos - 
for i in df_Arroyo_negla.columns[1:]:
    df_Arroyo_negla[i]=df_Arroyo_negla[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_Arroyo_negla[i]=df_Arroyo_negla[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_Arroyo_negla[i]=df_Arroyo_negla[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_Arroyo_negla[i]=df_Arroyo_negla[i].apply(formatData)
    df_Arroyo_negla[i] = df_Arroyo_negla[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_Arroyo_negla.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)

## Nuevo Data Frame de promedios por campana #2
df_Arroyo_negla_Prom=pd.DataFrame()

df_Arroyo_negla_Prom["PARÁMETROS"]=df_Arroyo_negla[first]
df_Arroyo_negla_Prom["RAINY SEASON 2021"]=df_Arroyo_negla[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_Arroyo_negla_Prom["DRY SEASON 2021"]=df_Arroyo_negla[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_Arroyo_negla_Prom["RAINY SEASON 2022"]=df_Arroyo_negla[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_Arroyo_negla_Prom
df_Arroyo_negla_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_Arroyo_negla.xlsx")
####################################################################################

PARÁMETROS FW 201-ST
PARÁMETROS FW 320-ST

In [19]:
### Analisis de Cuenca del Arroyo Hermosa - Merge de los dataframes ###

n=0
dropend=[]
dataBase=Arroyo_Hermosa
## MERGE
# print(Arroyo_Hermosa.keys())
df_Arroyo_Hermosa=pd.DataFrame()
for i in Arroyo_Hermosa.keys():
    if n==0:
        df_Arroyo_Hermosa=Arroyo_Hermosa[i]
        first=df_Arroyo_Hermosa.columns[0]
    if n>0:
        print(df_Arroyo_Hermosa[i].columns[0])
        df_Arroyo_Hermosa=df_Arroyo_Hermosa.merge(df_Arroyo_Hermosa[i], left_on=first, right_on=Arroyo_Hermosa[i].columns[0])
        dropend.append(Arroyo_Hermosa[i].columns[0])
    n+=1
    
## Elimnar las columas repetidas por el merge
df_Arroyo_Hermosa.drop(columns=dropend,inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_Arroyo_Hermosa.dropna(axis='columns',how='all').to_excel(f"{path2}\Original_Arroyo_Hermosa.xlsx")

## Limpieza de Datos - 
for i in df_Arroyo_Hermosa.columns[1:]:
    df_Arroyo_Hermosa[i]=df_Arroyo_Hermosa[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_Arroyo_Hermosa[i]=df_Arroyo_Hermosa[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_Arroyo_Hermosa[i]=df_Arroyo_Hermosa[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_Arroyo_Hermosa[i]=df_Arroyo_Hermosa[i].apply(formatData)
    df_Arroyo_Hermosa[i]=df_Arroyo_Hermosa[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_Arroyo_Hermosa.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)
        
## Nuevo Data Frame de promedios por campana #3
df_Arroyo_Hermosa_Prom=pd.DataFrame()

df_Arroyo_Hermosa_Prom["PARÁMETROS"]=df_Arroyo_Hermosa[first]
df_Arroyo_Hermosa_Prom["RAINY SEASON 2021"]=df_Arroyo_Hermosa[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_Arroyo_Hermosa_Prom["DRY SEASON 2021"]=df_Arroyo_Hermosa[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_Arroyo_Hermosa_Prom["RAINY SEASON 2022"]=df_Arroyo_Hermosa[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_Arroyo_Hermosa_Prom
df_Arroyo_Hermosa_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_Arroyo_Hermosa.xlsx")
####################################################################################

In [20]:
### Analisis de Cuenca del Arroyo_Trementina - Merge de los dataframes ###

n=0
dropend=[]
dataBase=Arroyo_Trementina
file='Arroyo_Trementina'
for i in dataBase.keys():
    dataBase[i].rename({dataBase[i].columns[1]: dataBase[i].columns[1]+'_'+i}, axis=1, inplace=True)
    dataBase[i].rename({dataBase[i].columns[2]: dataBase[i].columns[2]+'_'+i}, axis=1, inplace=True)
    dataBase[i].rename({dataBase[i].columns[3]: dataBase[i].columns[3]+'_'+i}, axis=1, inplace=True)
## MERGE
print(dataBase.keys())
df_dataBase=pd.DataFrame()
for i in dataBase.keys():
    if n==0:
        df_dataBase=dataBase[i]
        first=df_dataBase.columns[0]
        dropend.append(first)
#         print(first)
    elif n>0:
        print(dataBase[i].columns[0])
        df_dataBase=df_dataBase.merge(dataBase[i], left_on=dropend[n-1], right_on=dataBase[i].columns[0],suffixes=('_x', '_Y'))
        dropend.append(dataBase[i].columns[0])
    n+=1
dropend    
## Elimnar las columas repetidas por el merge
df_dataBase.drop(columns=dropend[1:],inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_dataBase.dropna(axis='columns',how='all').to_excel(f"{path2}\Original__{file}.xlsx")

## Limpieza de Datos - 
for i in df_dataBase.columns[1:]:
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_dataBase[i]=df_dataBase[i].apply(formatData)
    df_dataBase[i]=df_dataBase[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_dataBase.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)
        
## Nuevo Data Frame de promedios por campana #3
df_dataBase_Prom=pd.DataFrame()

df_dataBase_Prom["PARÁMETROS"]=df_dataBase[first]
df_dataBase_Prom["RAINY SEASON 2021"]=df_dataBase[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["DRY SEASON 2021"]=df_dataBase[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["RAINY SEASON 2022"]=df_dataBase[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_dataBase_Prom
df_dataBase_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_{file}.xlsx")
df_Arroyo_Trementina_Prom=df_dataBase_Prom
####################################################################################

dict_keys(['FW 100-GASL', 'FW 109-MYRZ', 'FW 200-SLTR', 'FW 205-TR', 'FW 208-TR', 'FW 304-HE', 'FW 317-RZ'])
PARÁMETROS FW 109-MYRZ
PARÁMETROS FW 200-SLTR
PARÁMETROS FW 205-TR
PARÁMETROS FW 208-TR
PARÁMETROS FW 304-HE
PARÁMETROS FW 317-RZ

In [21]:
### Analisis de Cuenca del Arroyo_Pitanohaga - Merge de los dataframes ###

n=0
dropend=[]
dataBase=Arroyo_Pitanohaga
file='Arroyo_Pitanohaga'
for i in dataBase.keys():
    dataBase[i].rename({dataBase[i].columns[1]: dataBase[i].columns[1]+'_'+i}, axis=1, inplace=True)
    dataBase[i].rename({dataBase[i].columns[2]: dataBase[i].columns[2]+'_'+i}, axis=1, inplace=True)
    dataBase[i].rename({dataBase[i].columns[3]: dataBase[i].columns[3]+'_'+i}, axis=1, inplace=True)

    
## MERGE
print(dataBase.keys())
df_dataBase=pd.DataFrame()
for i in dataBase.keys():
    if n==0:
        df_dataBase=dataBase[i]
        first=df_dataBase.columns[0]
        dropend.append(first)
        print(first)
    elif n>0:
        print(dataBase[i].columns[0])
        df_dataBase=df_dataBase.merge(dataBase[i], left_on=dropend[n-1], right_on=dataBase[i].columns[0],suffixes=('_x', '_Y'))
        dropend.append(dataBase[i].columns[0])
    n+=1
dropend    
## Elimnar las columas repetidas por el merge
df_dataBase.drop(columns=dropend[1:],inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_dataBase.dropna(axis='columns',how='all').to_excel(f"{path2}\Original__{file}.xlsx")

## Limpieza de Datos - 
for i in df_dataBase.columns[1:]:
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_dataBase[i]=df_dataBase[i].apply(formatData)
    df_dataBase[i]=df_dataBase[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_dataBase.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)
        
## Nuevo Data Frame de promedios por campana #3
df_dataBase_Prom=pd.DataFrame()

df_dataBase_Prom["PARÁMETROS"]=df_dataBase[first]
df_dataBase_Prom["RAINY SEASON 2021"]=df_dataBase[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["DRY SEASON 2021"]=df_dataBase[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["RAINY SEASON 2022"]=df_dataBase[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_dataBase_Prom
df_dataBase_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_{file}.xlsx")
df_Arroyo_Pitanohaga_Prom=df_dataBase_Prom

####################################################################################

dict_keys(['FW 210-ZM', 'FW 212-MC', 'FW 318-VS', 'FW 319-SO'])
PARÁMETROS FW 210-ZM
PARÁMETROS FW 212-MC
PARÁMETROS FW 318-VS
PARÁMETROS FW 319-SO

In [22]:
### Analisis de Cuenca del Rio_Aquidaban - Merge de los dataframes ###
n=0
dropend=[]
dataBase=Rio_Aquidaban
file='Rio_Aquidaban'
## MERGE
print(dataBase.keys())
df_dataBase=pd.DataFrame()
for i in dataBase.keys():
    if n==0:
        df_dataBase=dataBase[i]
        first=df_dataBase.columns[0]
        dropend.append(first)
#         print(first)
    elif n>0:
        print(dataBase[i].columns[0])
        df_dataBase=df_dataBase.merge(dataBase[i], left_on=dropend[n-1], right_on=dataBase[i].columns[0],suffixes=('_x', '_Y'))
#         df_dataBase[i].columns[0]=df_dataBase[i].columns[0]+'_1'
        dropend.append(dataBase[i].columns[0])
    n+=1
dropend    
## Elimnar las columas repetidas por el merge
df_dataBase.drop(columns=dropend[1:],inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
# df_dataBase.iloc[:, 1:].dropna(axis='index',how='all',inplace=True)
df_dataBase.dropna(axis='columns',how='all').to_excel(f"{path2}\Original__{file}.xlsx")

## Limpieza de Datos - 
for i in df_dataBase.columns[1:]:
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_dataBase[i]=df_dataBase[i].apply(formatData)
    df_dataBase[i]=df_dataBase[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_dataBase.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)
        
## Nuevo Data Frame de promedios por campana #3
df_dataBase_Prom=pd.DataFrame()

df_dataBase_Prom["PARÁMETROS"]=df_dataBase[first]
df_dataBase_Prom["RAINY SEASON 2021"]=df_dataBase[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["DRY SEASON 2021"]=df_dataBase[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["RAINY SEASON 2022"]=df_dataBase[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_dataBase_Prom
df_dataBase_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_{file}.xlsx")
df_Rio_Aquidaban_Prom=df_dataBase_Prom

####################################################################################

dict_keys(['FW 110-LB', 'FW 111-LB'])
PARÁMETROS FW 111-LB

In [23]:
### Analisis de Cuenca del Arroyo Laguna Penayo - Merge de los dataframes ###
n=0
dropend=[]
dataBase=Arroyo_Laguna_Penayo
file='Arroyo_Laguna_Penayo'
## MERGE
print(dataBase.keys())
df_dataBase=pd.DataFrame()
for i in dataBase.keys():
    if n==0:
        df_dataBase=dataBase[i]
        first=df_dataBase.columns[0]
        dropend.append(first)
#         print(first)
    elif n>0:
        print(dataBase[i].columns[0])
        df_dataBase=df_dataBase.merge(dataBase[i], left_on=dropend[n-1], right_on=dataBase[i].columns[0],suffixes=('_x', '_Y'))
        dropend.append(dataBase[i].columns[0])
    n+=1
dropend    
## Elimnar las columas repetidas por el merge
df_dataBase.drop(columns=dropend[1:],inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_dataBase.dropna(axis='columns',how='all').to_excel(f"{path2}\Original__{file}.xlsx")

## Limpieza de Datos - 
for i in df_dataBase.columns[1:]:
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_dataBase[i]=df_dataBase[i].apply(formatData)
    df_dataBase[i]=df_dataBase[i].astype(float)

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_dataBase.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i:
        val_RAINY_SEASON_2022.append(i)
        
## Nuevo Data Frame de promedios por campana #3
df_dataBase_Prom=pd.DataFrame()

df_dataBase_Prom["PARÁMETROS"]=df_dataBase[first]
df_dataBase_Prom["RAINY SEASON 2021"]=df_dataBase[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["DRY SEASON 2021"]=df_dataBase[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["RAINY SEASON 2022"]=df_dataBase[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_dataBase_Prom
df_dataBase_Prom.dropna(axis='columns',how='all').to_excel(f"{path2}\Promedios_{file}.xlsx")
df_Arroyo_Laguna_Penayo_Prom=df_dataBase_Prom

####################################################################################

dict_keys(['FW 316-CR'])

In [24]:
# promedios=[df_Rio_Paraguay_Prom,
# df_Arroyo_negla_Prom,
# df_Arroyo_Hermosa_Prom,
# df_Arroyo_Trementina_Prom,
# df_Arroyo_Pitanohaga_Prom,
# df_Rio_Aquidaban_Prom,
# df_Arroyo_Laguna_Penayo_Prom]

promedios=[df_Rio_Paraguay_Prom.dropna(axis='index',how='all'),
df_Arroyo_negla_Prom.dropna(axis='index',how='all'),
df_Arroyo_Hermosa_Prom.dropna(axis='index',how='all'),
df_Arroyo_Trementina_Prom.dropna(axis='index',how='all'),
df_Arroyo_Pitanohaga_Prom.dropna(axis='index',how='all'),
df_Rio_Aquidaban_Prom.dropna(axis='index',how='all'),
df_Arroyo_Laguna_Penayo_Prom.dropna(axis='index',how='all')]

columnas=['Rio_Paraguay',
'Arroyo_neglam',
'Arroyo_Hermosa',
'Arroyo_Trementina',
'Arroyo_Pitanohaga',
'Rio_Aquidaban',
'Arroyo_Laguna_Penayo']

parametros=df_dataBase_Prom['PARÁMETROS']
parametros.dropna(inplace=True)
limites.dropna(inplace=True)

In [26]:
for i in parametros.index:
    Resultado=pd.DataFrame()
    Resultado['Campana']=df_dataBase_Prom.columns
#     print(i)
    if i!= 36 or i!= 39:
        for j in range(len(columnas)):
            aux=promedios[j][(promedios[j]["PARÁMETROS"].isin([parametros[i]]))]
    #         print(str(j)+'_'+str(aux))
            try:
                lista=('Promedio',float(aux['RAINY SEASON 2021'].values),float(aux['DRY SEASON 2021'].values),float(aux['RAINY SEASON 2022'].values))
                Resultado[columnas[j]]=lista
            except:
                pass

        Resultado['Limite']=['',limites[i],limites[i],limites[i]]
        suma1,suma2,suma3,porc2,porc1,porc3=np.NaN,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN
        if type(limites[i])== int or type(limites[i])== float:
            suma1=Resultado[1:].apply(lambda x: x[columnas][2] > limites[i], axis=1).sum()
            suma2=Resultado[1:].apply(lambda x: x[columnas][3] > limites[i], axis=1).sum()
            suma3=Resultado[1:].apply(lambda x: x[columnas][4] > limites[i], axis=1).sum()
#             suma1=df_dataBase.apply(lambda x: x[columnas][val_RAINY_SEASON_2021] > limites[i], axis=1).sum()
#             suma2=df_dataBase.apply(lambda x: x[columnas][val_DRY_SEASON_2021] > limites[i], axis=1).sum()
#             suma3=df_dataBase.apply(lambda x: x[columnas][val_RAINY_SEASON_2022] > limites[i], axis=1).sum()
            porc1=round(100*suma1/len(columnas),2)
            porc2=round(100*suma2/len(columnas),2)
            porc3=round(100*suma3/len(columnas),2)
        Resultado['Fuera']=['Nº',suma1,suma2,suma3]
        Resultado['del limite']=['(%)',porc1,porc2,porc3]
        Resultado.to_excel(f"{path3}\Resultado_{parametros[i]}.xlsx")
        print("generado "+ str(i+1) +' de '+ str(len(parametros)))

generado 1 de 67
generado 2 de 67
generado 3 de 67
generado 4 de 67
generado 5 de 67
generado 6 de 67
generado 7 de 67
generado 8 de 67
generado 9 de 67
generado 10 de 67
generado 11 de 67
generado 12 de 67
generado 13 de 67
generado 14 de 67
generado 15 de 67
generado 16 de 67
generado 17 de 67
generado 18 de 67
generado 19 de 67
generado 20 de 67
generado 21 de 67
generado 22 de 67
generado 23 de 67
generado 24 de 67
generado 25 de 67
generado 26 de 67
generado 27 de 67
generado 28 de 67
generado 29 de 67
generado 30 de 67
generado 31 de 67
generado 32 de 67
generado 33 de 67
generado 34 de 67
generado 35 de 67
generado 36 de 67
generado 38 de 67
generado 39 de 67
generado 41 de 67
generado 42 de 67
generado 43 de 67
generado 44 de 67
generado 45 de 67
generado 46 de 67
generado 47 de 67
generado 48 de 67
generado 49 de 67
generado 50 de 67
generado 51 de 67
generado 52 de 67
generado 53 de 67
generado 54 de 67
generado 55 de 67
generado 56 de 67
generado 57 de 67
generado 58 de 67
generado 59 de 67
generado 60 de 67
generado 61 de 67
generado 62 de 67
generado 63 de 67
generado 64 de 67
generado 65 de 67
generado 66 de 67
generado 67 de 67
generado 68 de 67
generado 69 de 67

In [89]:
 for i in limites:
    if type(i)== int:
        suma1=Resultado[1:].apply(lambda x: x[columnas][2] > i, axis=1).sum()
        suma2=Resultado[1:].apply(lambda x: x[columnas][3] > i, axis=1).sum()
        suma3=Resultado[1:].apply(lambda x: x[columnas][4] > i, axis=1).sum()
        porc1=round(100*suma1/len(Todo),2)
        porc2=round(100*suma2/len(Todo),2)
        porc3=round(100*suma3/len(Todo),2)

100
500
5
10
1
300
200
1
3
250
2
2
2
700
2
0
2
3
4
4
0
30
10
1

In [127]:
suma1=Resultado[1:].apply(lambda x: x[columnas][2] > 0.02, axis=1).sum()
suma2=Resultado[1:].apply(lambda x: x[columnas][3] > 0.02, axis=1).sum()
suma3=Resultado[1:].apply(lambda x: x[columnas][4] > 0.02, axis=1).sum()

In [133]:
df_dataBase[val_DRY_SEASON_2021].to_excel(f"{path2}\Resumen_{file}_DRY_2021.xlsx")
df_dataBase[val_RAINY_SEASON_2021].to_excel(f"{path2}\Resumen_{file}_RAINY_2021.xlsx")
df_dataBase[val_RAINY_SEASON_2022].to_excel(f"{path2}\Resumen_{file}_RAINY_2022.xlsx")

14.29

In [250]:
df_dataBase

,PARÁMETROS FW 01-PY,RAINY SEASON 2021_df_1,DRY SEASON_df_1,FEB_df_1,RAINY SEASON 2021_df_2,DRY SEASON 2022_df_2,FEB_df_2,RAINY SEASON 2021_df_3,DRY SEASON 2021_df_3,FEB_df_3,...,RAINY SEASON 2022_df_24,RAINY SEASON 2021_df_25,DRY SEASON 2021_df_25,RAINY SEASON 2022_df_25,RAINY SEASON 2021_df_26,DRY SEASON 2021_df_26,RAINY SEASON 2022_df_26,RAINY SEASON 2021_df_27,DRY SEASON 2021_df_27,RAINY SEASON 2022_df_27
0,Temperatura del agua,26.00,19.70,30.90,25.00,19.20,30.80,NaN,NaN,30.70,...,24.40,NaN,NaN,NaN,NaN,20.00,29.30,NaN,14.50,28.50
1,Potencial de hidrogeno,7.26,6.94,7.10,7.29,7.07,7.06,NaN,NaN,7.14,...,6.58,NaN,NaN,NaN,NaN,7.75,7.04,NaN,7.48,7.34
2,Conductividad eléctrica,169.30,114.00,87.30,171.80,316.00,92.00,NaN,NaN,90.20,...,104.60,NaN,NaN,NaN,NaN,451.00,178.10,NaN,106.00,53.40
3,Oxígeno disuelto,7.03,9.47,6.35,7.26,9.53,6.40,NaN,NaN,6.49,...,5.20,NaN,NaN,NaN,NaN,7.64,7.15,NaN,7.60,7.54
4,Turbidez,41.20,14.10,15.20,44.60,15.50,23.40,NaN,NaN,25.60,...,22.80,NaN,NaN,NaN,NaN,1.59,4.21,NaN,9.16,15.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Imidacloprid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Metilparaoxon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Tiametoxam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Sulfluramida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Fipronil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in len(df_dataBase):
    Suma+=df_dataBase[1:].apply(lambda x: x[Todo[.keys()]][2] > 2, axis=1).sum()

In [251]:
len(Todo)

21

In [224]:
df_dataBase.columns

Index(['PARÁMETROS FW 01-PY', 'RAINY SEASON 2021_df_1', 'DRY SEASON_df_1',
       'FEB_df_1', 'RAINY SEASON 2021_df_2', 'DRY SEASON 2022_df_2',
       'FEB_df_2', 'RAINY SEASON 2021_df_3', 'DRY SEASON 2021_df_3',
       'FEB_df_3', 'RAINY SEASON 2021_df_4', 'DRY SEASON 2021_df_4',
       'RAINY SEASON 2022_df_4', 'RAINY SEASON 2021_df_5',
       'DRY SEASON 2021_df_5', 'RAINY SEASON 2022_df_5',
       'RAINY SEASON 2021_df_6', 'DRY SEASON 2021_df_6',
       'RAINY SEASON 2022_df_6', 'RAINY SEASON 2021_df_7',
       'DRY SEASON 2021_df_7', 'RAINY SEASON 2022_df_7',
       'RAINY SEASON 2021_df_8', 'DRY SEASON 2021_df_8',
       'RAINY SEASON 2022_df_8', 'RAINY SEASON 2021_df_10',
       'DRY SEASON 2021_df_10', 'RAINY SEASON 2022_df_10',
       'RAINY SEASON 2021_df_11', 'DRY SEASON 2021_df_11',
       'RAINY SEASON 2022_df_11', 'RAINY SEASON 2021_df_13',
       'DRY SEASON 2021_df_13', 'RAINY SEASON 2022_df_13',
       'RAINY SEASON 2021_df_15', 'DRY SEASON 2021_df_15',
       'RAINY SEASON 2022_df_15', 'RAINY SEASON 2021_df_16',
       'DRY SEASON 2021_df_16', 'RAINY SEASON 2022_df_16',
       'RAINY SEASON 2021_df_18', 'DRY SEASON 2021_df_18',
       'RAINY SEASON 2022_df_18', 'RAINY SEASON 2021_df_19',
       'DRY SEASON 2021_df_19', 'RAINY SEASON 2022_df_19',
       'RAINY SEASON 2021_df_22', 'DRY SEASON 2021_df_22',
       'RAINY SEASON 2022_df_22', 'RAINY SEASON 2021_df_23',
       'DRY SEASON 2021_df_23', 'RAINY SEASON 2022_df_23',
       'RAINY SEASON 2021_df_24', 'DRY SEASON 2021_df_24',
       'RAINY SEASON 2022_df_24', 'RAINY SEASON 2021_df_25',
       'DRY SEASON 2021_df_25', 'RAINY SEASON 2022_df_25',
       'RAINY SEASON 2021_df_26', 'DRY SEASON 2021_df_26',
       'RAINY SEASON 2022_df_26', 'RAINY SEASON 2021_df_27',
       'DRY SEASON 2021_df_27', 'RAINY SEASON 2022_df_27'],
      dtype='object')

In [14]:
### Analisis de Cuenca del Todo - Merge de los dataframes ###

for n in Todo:
    try:
        Todo[n].dropna(axis='columns',how='all',inplace=True)
        Todo[n].drop(columns=['Unnamed: 0','Nº','SÍMBOLO','UNIDAD DE MEDIDA','LIMITES RESOLUCIÓN 222/02'],inplace=True)
        Todo[n].drop(columns=['MAR'],inplace=True)
    except:
        pass
n=0
dropend=[]
dataBase=Todo
file='Todo'

# for i in dataBase.keys():
#     dataBase[i].rename({dataBase[i].columns[1]: dataBase[i].columns[1]+'_'+i}, axis=1, inplace=True)
#     dataBase[i].rename({dataBase[i].columns[2]: dataBase[i].columns[2]+'_'+i}, axis=1, inplace=True)
#     try:
#         dataBase[i].rename({dataBase[i].columns[3]: dataBase[i].columns[3]+'_'+i}, axis=1, inplace=True)
#     except:
#         pass

## MERGE
print(dataBase.keys())
df_dataBase=pd.DataFrame()
for i in dataBase.keys():
    if n==0:
        df_dataBase=dataBase[i]
        first=df_dataBase.columns[0]
        dropend.append(first)
#         print(first)
    elif n>0:
        print(dataBase[i].columns[0])
        df_dataBase=df_dataBase.merge(dataBase[i], left_on=dropend[n-1], right_on=dataBase[i].columns[0],suffixes=('_x', '_Y'))
        dropend.append(dataBase[i].columns[0])
    n+=1
dropend    
## Elimnar las columas repetidas por el merge
df_dataBase.drop(columns=dropend[1:],inplace=True)

## Generar Archivo Data Set ORIGINAL Cause #1
df_dataBase.dropna(axis='columns',how='all').to_excel(f"{path2}\Original_{file}.xlsx")

## Generar Variables de columnas 
val_RAINY_SEASON_2021=[]
val_DRY_SEASON_2021=[]
val_RAINY_SEASON_2022=[]

for i in df_dataBase.columns:
    if 'RAINY SEASON 2021' in i:
        val_RAINY_SEASON_2021.append(i)
    if 'DRY SEASON 2021' in i:
        val_DRY_SEASON_2021.append(i)
    if 'RAINY SEASON 2022' in i or 'FEB' in i:
        val_RAINY_SEASON_2022.append(i)
        
df_todo_DRY_SEASON_2021=df_dataBase[[first]+val_DRY_SEASON_2021]
df_todo_RAINY_SEASON_2021=df_dataBase[[first]+val_RAINY_SEASON_2021]
df_todo_RAINY_SEASON_2022=df_dataBase[[first]+val_RAINY_SEASON_2022]
df_dataBase[[first]+val_DRY_SEASON_2021].to_excel(f"{path2}\Original_{file}_DRY_2021.xlsx")
df_dataBase[[first]+val_RAINY_SEASON_2021].to_excel(f"{path2}\Original_{file}_RAINY_2021.xlsx")
df_dataBase[[first]+val_RAINY_SEASON_2022].to_excel(f"{path2}\Original_{file}_RAINY_2022.xlsx")  

## Limpieza de Datos - 
for i in df_dataBase.columns[1:]:
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S.D.' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D' else x)
    df_dataBase[i]=df_dataBase[i].apply(lambda x: np.NaN if x=='S/D - NIT' else x)
    df_dataBase[i]=df_dataBase[i].apply(formatData)
    df_dataBase[i]=df_dataBase[i].astype(float)


        
## Nuevo Data Frame de promedios por campana #3
df_dataBase_Prom=pd.DataFrame()

df_dataBase_Prom["PARÁMETROS"]=df_dataBase[first]
df_dataBase_Prom["RAINY SEASON 2021"]=df_dataBase[val_RAINY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["DRY SEASON 2021"]=df_dataBase[val_DRY_SEASON_2021].mean(axis=1,numeric_only=True,skipna=True)
df_dataBase_Prom["RAINY SEASON 2022"]=df_dataBase[val_RAINY_SEASON_2022].mean(axis=1,numeric_only=True,skipna=True)

# Generar Archivo Data Set Promedios Cause #1
df_dataBase_Prom
df_dataBase_Prom.to_excel(f"{path2}\Promedios_{file}.xlsx")
df_Todo_Prom=df_dataBase_Prom

####################################################################################
# Espacial Resumen 
df_dataBase[val_DRY_SEASON_2021].to_excel(f"{path2}\Resumen_{file}_DRY_2021.xlsx")
df_dataBase[val_RAINY_SEASON_2021].to_excel(f"{path2}\Resumen_{file}_RAINY_2021.xlsx")
df_dataBase[val_RAINY_SEASON_2022].to_excel(f"{path2}\Resumen_{file}_RAINY_2022.xlsx")

df_todo_DRY_SEASON_2021=df_dataBase[[first]+val_DRY_SEASON_2021]
df_todo_RAINY_SEASON_2021=df_dataBase[[first]+val_RAINY_SEASON_2021]
df_todo_RAINY_SEASON_2022=df_dataBase[[first]+val_RAINY_SEASON_2022]

dict_keys(['FW 01', 'FW 02', 'FW 03', 'FW 100-GASL', 'FW 104-ZA', 'FW 109-MYRZ', 'FW 110-LB', 'FW 111-LB', 'FW 200-SLTR', 'FW 201-ST', 'FW 205-TR', 'FW 208-TR', 'FW 210-ZM', 'FW 212-MC', 'FW 304-HE', 'FW 315-HE', 'FW 316-CR', 'FW 317-RZ', 'FW 318-VS', 'FW 319-SO', 'FW 320-ST'])
PARÁMETROS FW 02-PY
PARÁMETROS FW 03-PY
PARÁMETROS FW 100-GASL
PARÁMETROS FW 104-ZA
PARÁMETROS FW 109-MYRZ
PARÁMETROS FW 110-LB
PARÁMETROS FW 111-LB
PARÁMETROS FW 200-SLTR
PARÁMETROS FW 201-ST
PARÁMETROS FW 205-TR
PARÁMETROS FW 208-TR
PARÁMETROS FW 210-ZM
PARÁMETROS FW 212-MC
PARÁMETROS FW 304-HE
PARÁMETROS FW 315-HE
PARÁMETROS FW 316-CR
PARÁMETROS FW 317-RZ
PARÁMETROS FW 318-VS
PARÁMETROS FW 319-SO
PARÁMETROS FW 320-ST

In [268]:
df_todo_DRY_SEASON_2021.transpose().plot()
plt.show()

TypeError: no numeric data to plot

In [328]:
dx=df_todo_DRY_SEASON_2021.transpose()
col=df_todo_DRY_SEASON_2021.transpose()[0:1].values
dx.rename(columns=dx.iloc[0], inplace=True)
dx.drop(dx.iloc[0])

KeyError: "['Temperatura del agua' 'Potencial de hidrogeno' 'Conductividad eléctrica'\n 'Oxígeno disuelto' 'Turbidez' 'Materiales flotantes '\n 'Sólidos disueltos totales ' 'Aceites y grasas '\n 'Demanda química de oxigeno' 'Demanda biológica de oxigeno'\n 'Fósforo total ' 'Ortosfato (fosfato)' 'Nitrógeno total ' 'Nitratos '\n 'Nitritos ' 'Amoniaco ' 'Clorofila a' 'Dureza ' 'Sodio' 'Aluminio'\n 'Cadmio' 'Cromo hexavalente' 'Cromo trivalente' 'Cobre' 'Níquel'\n 'Manganeso' 'Plomo' 'Zinc' 'Arsénico' 'Hierro soluble' 'Sulfatos'\n 'Estaño' 'Selenio' 'Mercurio' 'Bario' 'Cianuros' 'Coliformes totales'\n 'Coliformes fecales ' 'Glifosato ' 'AMPA ' 'Aldrin' 'Endrin' 'Dieldrin'\n 'Lindano' 'Clordano' 'DDT' 'DDE' 'DDD' 'Atrazina' 'Simazina' 'Carbaril'\n 'Carbofuran' 'Heptacloro' 'Metomilo' '2,4 D ' 'Lambdacialotrina '\n 'Bifentrin ' 'Cipermetrina' 'Clorpirifos' 'Diclorvos' 'Metamidofos'\n 'Tebuconazole' 'Imidacloprid' 'Metilparaoxon' 'Tiametoxam '\n 'Sulfluramida ' 'Fipronil'] not found in axis"

In [329]:
dx.drop(dx.iloc[0])

KeyError: "['Temperatura del agua' 'Potencial de hidrogeno' 'Conductividad eléctrica'\n 'Oxígeno disuelto' 'Turbidez' 'Materiales flotantes '\n 'Sólidos disueltos totales ' 'Aceites y grasas '\n 'Demanda química de oxigeno' 'Demanda biológica de oxigeno'\n 'Fósforo total ' 'Ortosfato (fosfato)' 'Nitrógeno total ' 'Nitratos '\n 'Nitritos ' 'Amoniaco ' 'Clorofila a' 'Dureza ' 'Sodio' 'Aluminio'\n 'Cadmio' 'Cromo hexavalente' 'Cromo trivalente' 'Cobre' 'Níquel'\n 'Manganeso' 'Plomo' 'Zinc' 'Arsénico' 'Hierro soluble' 'Sulfatos'\n 'Estaño' 'Selenio' 'Mercurio' 'Bario' 'Cianuros' 'Coliformes totales'\n 'Coliformes fecales ' 'Glifosato ' 'AMPA ' 'Aldrin' 'Endrin' 'Dieldrin'\n 'Lindano' 'Clordano' 'DDT' 'DDE' 'DDD' 'Atrazina' 'Simazina' 'Carbaril'\n 'Carbofuran' 'Heptacloro' 'Metomilo' '2,4 D ' 'Lambdacialotrina '\n 'Bifentrin ' 'Cipermetrina' 'Clorpirifos' 'Diclorvos' 'Metamidofos'\n 'Tebuconazole' 'Imidacloprid' 'Metilparaoxon' 'Tiametoxam '\n 'Sulfluramida ' 'Fipronil'] not found in axis"

In [307]:
p=0
auxCol=[]
for i in col[0]:
    print (i)
    auxCol.append(i)
    p+=1
# col[0][1]

Temperatura del agua
Potencial de hidrogeno
Conductividad eléctrica
Oxígeno disuelto
Turbidez
Materiales flotantes
Sólidos disueltos totales
Aceites y grasas
Demanda química de oxigeno
Demanda biológica de oxigeno
Fósforo total
Ortosfato (fosfato)
Nitrógeno total
Nitratos
Nitritos
Amoniaco
Clorofila a
Dureza
Sodio
Aluminio
Cadmio
Cromo hexavalente
Cromo trivalente
Cobre
Níquel
Manganeso
Plomo
Zinc
Arsénico
Hierro soluble
Sulfatos
Estaño
Selenio
Mercurio
Bario
Cianuros
Coliformes totales
Coliformes fecales
Glifosato
AMPA
Aldrin
Endrin
Dieldrin
Lindano
Clordano
DDT
DDE
DDD
Atrazina
Simazina
Carbaril
Carbofuran
Heptacloro
Metomilo
2,4 D
Lambdacialotrina
Bifentrin
Cipermetrina
Clorpirifos
Diclorvos
Metamidofos
Tebuconazole
Imidacloprid
Metilparaoxon
Tiametoxam
Sulfluramida
Fipronil

In [320]:
str(dx.columns.values)

'[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23\n 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47\n 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66]'

In [322]:
dx

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
PARÁMETROS FW 01-PY,Temperatura del agua,Potencial de hidrogeno,Conductividad eléctrica,Oxígeno disuelto,Turbidez,Materiales flotantes,Sólidos disueltos totales,Aceites y grasas,Demanda química de oxigeno,Demanda biológica de oxigeno,...,Cipermetrina,Clorpirifos,Diclorvos,Metamidofos,Tebuconazole,Imidacloprid,Metilparaoxon,Tiametoxam,Sulfluramida,Fipronil
DRY SEASON 2021_df_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_4,14.3,7.45,1063.0,6.15,0.58,2.86,241.0,15.2,11.1,1.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_5,13.3,7.28,120.0,7.1,13.4,12.5,127.0,6.25,11.4,1.92,...,NaN,NaN,NaN,NaN,66.5,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_6,15.6,7.44,362.0,5.43,7.4,2.4,117.0,8.9,23.3,2.68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03
DRY SEASON 2021_df_7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_8,18.0,7.38,230.0,9.35,12.5,5.0,105.0,18.8,14.1,1.79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_11,12.6,7.82,194.0,7.3,3.74,5.5,113.0,15.0,21.9,3.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_15,16.3,7.2,599.0,5.0,0.7,1.2,178.0,7.5,14.6,1.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_16,19.5,7.27,606.0,5.64,4.04,2.8,203.0,19.2,18.3,1.14,...,1058.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_18,17.9,7.7,476.0,7.7,120.0,19.6,336.0,16.2,64.1,2.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_19,13.6,7.55,1154.0,6.71,5.47,4.5,130.0,8.25,16.0,2.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_22,15.8,6.97,222.0,3.49,13.1,4.5,122.0,3.5,31.8,4.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_23,18.3,6.89,129.0,6.3,34.1,6.0,165.0,10.8,35.5,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_24,16.6,7.16,172.0,4.8,21.8,24.4,250.0,12.0,72.8,3.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_26,20.0,7.75,451.0,7.64,1.59,0.4,171.0,11.0,21.7,1.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DRY SEASON 2021_df_27,14.5,7.48,106.0,7.6,9.16,7.5,114.0,4.25,4.55,2.45,...,NaN,NaN,NaN,NaN,298.7,NaN,NaN,NaN,NaN,NaN

In [247]:
# [to_insert] + int_list

df_dataBase[[first]+val_DRY_SEASON_2021]

,PARÁMETROS FW 01-PY,DRY SEASON 2021_df_3,DRY SEASON 2021_df_4,DRY SEASON 2021_df_5,DRY SEASON 2021_df_6,DRY SEASON 2021_df_7,DRY SEASON 2021_df_8,DRY SEASON 2021_df_10,DRY SEASON 2021_df_11,DRY SEASON 2021_df_13,DRY SEASON 2021_df_15,DRY SEASON 2021_df_16,DRY SEASON 2021_df_18,DRY SEASON 2021_df_19,DRY SEASON 2021_df_22,DRY SEASON 2021_df_23,DRY SEASON 2021_df_24,DRY SEASON 2021_df_25,DRY SEASON 2021_df_26,DRY SEASON 2021_df_27
0,Temperatura del agua,NaN,14.30,13.30,15.60,NaN,18.00,NaN,12.60,NaN,16.3,19.50,17.9,13.60,15.80,18.30,16.60,NaN,20.00,14.50
1,Potencial de hidrogeno,NaN,7.45,7.28,7.44,NaN,7.38,NaN,7.82,NaN,7.2,7.27,7.7,7.55,6.97,6.89,7.16,NaN,7.75,7.48
2,Conductividad eléctrica,NaN,1063.00,120.00,362.00,NaN,230.00,NaN,194.00,NaN,599.0,606.00,476.0,1154.00,222.00,129.00,172.00,NaN,451.00,106.00
3,Oxígeno disuelto,NaN,6.15,7.10,5.43,NaN,9.35,NaN,7.30,NaN,5.0,5.64,7.7,6.71,3.49,6.30,4.80,NaN,7.64,7.60
4,Turbidez,NaN,0.58,13.40,7.40,NaN,12.50,NaN,3.74,NaN,0.7,4.04,120.0,5.47,13.10,34.10,21.80,NaN,1.59,9.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Imidacloprid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Metilparaoxon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Tiametoxam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Sulfluramida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Fipronil,NaN,NaN,NaN,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
mapa

{'df_0': 'DataSet',
 'df_1': 'FW 01.xlsx',
 'df_2': 'FW 02.xlsx',
 'df_3': 'FW 03.xlsx',
 'df_4': 'FW 100-GASL.xlsx',
 'df_5': 'FW 104-ZA.xlsx',
 'df_6': 'FW 109-MYRZ.xlsx',
 'df_7': 'FW 110-LB.xlsx',
 'df_8': 'FW 111-LB.xlsx',
 'df_9': 'FW 115-MY.xlsx',
 'df_10': 'FW 200-SLTR.xlsx',
 'df_11': 'FW 201-ST.xlsx',
 'df_12': 'FW 204-LB.xlsx',
 'df_13': 'FW 205-TR.xlsx',
 'df_14': 'FW 207-TR.xlsx',
 'df_15': 'FW 208-TR.xlsx',
 'df_16': 'FW 210-ZM.xlsx',
 'df_17': 'FW 211-VS.xlsx',
 'df_18': 'FW 212-MC.xlsx',
 'df_19': 'FW 304-HE.xlsx',
 'df_20': 'FW 306-SO.xlsx',
 'df_21': 'FW 310-CR.xlsx',
 'df_22': 'FW 315-HE.xlsx',
 'df_23': 'FW 316-CR.xlsx',
 'df_24': 'FW 317-RZ.xlsx',
 'df_25': 'FW 318-VS.xlsx',
 'df_26': 'FW 319-SO.xlsx',
 'df_27': 'FW 320-ST.xlsx',
 'df_28': 'Resultados'}

In [8]:
Puntos

{'Rio_Paraguay': ('FW 01.xlsx', 'FW 02.xlsx', 'FW 03.xlsx'),
 'Arroyo_negla': ('FW 104-ZA.xlsx', 'FW 201-ST.xlsx', 'FW 320-ST.xlsx'),
 'Arroyo_Hermosa': ('FW 315-HE.xlsx',),
 'Arroyo_Trementina': ('FW 304-HE.xlsx',
  'FW 100-GASL.xlsx',
  'FW 200-SLTR.xlsx',
  'FW 208-TR.xlsx',
  'FW 205-TR.xlsx',
  'FW 109-MYRZ.xlsx',
  'FW 317-RZ.xlsx'),
 'Arroyo_Pitanohaga': ('FW 210-ZM.xlsx',
  'FW 212-MC.xlsx',
  'FW 318-VS.xlsx',
  'FW 319-SO.xlsx'),
 'Rio_Aquidaban': ('FW 110-LB.xlsx', 'FW 111-LB.xlsx'),
 'Arroyo_Laguna_Penayo': 'FW 316-CR.xlsx'}